name: Terraform Destroy (Safe Clean-up)

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Environment stage to destroy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
      confirm_destroy:
        description: "Type 'DESTROY' to confirm resource deletion"
        required: true
        default: "NO"
        type: string

env:
  AWS_REGION: eu-north-1

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm_destroy == 'DESTROY' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: assignment-3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform
        working-directory: Assignment-3/terraform
        run: terraform init

      - name: Terraform Destroy
        working-directory: Assignment-3/terraform
        run: terraform destroy -auto-approve \
          -var="stage=${{ github.event.inputs.stage }}" \
          -var="key_name=${{ vars.AWS_KEY_PAIR }}" \
          -var="s3_bucket_name=techeazy-logs-devops"

    # Safety guard — only proceed when confirmation matches
    if: ${{ github.event.inputs.confirm_destroy == 'DESTROY' }}

  cancel-destroy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm_destroy != 'DESTROY' }}
    steps:
      - name: Cancel Destroy
        run: echo "❌ Destroy cancelled. To proceed, rerun and type DESTROY in confirmation input."

