name: Terraform Destroy

on:
  workflow_dispatch: # Only manual trigger

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
    defaults:
      run:
        working-directory: Assignment-3/terraform  # Terraform folder path

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: assignment-3   # Checkout the branch with Terraform code

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve \
          -var="region=${{ secrets.AWS_REGION }}" \
          -var="stage=${{ secrets.STAGE }}" \
          -var="ami_id=${{ secrets.AMI_ID }}" \
          -var="instance_type=${{ secrets.INSTANCE_TYPE }}" \
          -var="key_name=${{ secrets.EC2_KEY_NAME }}" \
          -var="existing_bucket_name=${{ secrets.EXISTING_BUCKET_NAME }}" \
          -var="github_repo=${{ secrets.REPO_GITHUB }}"

