name: Terraform Destroy

on:
  workflow_dispatch: # Only manual trigger

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1

    defaults:
      run:
        working-directory: Assignment-3  # Terraform folder path

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: assignment-3   # Checkout the branch with Terraform code

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve \
          -var="ami_id=${{ secrets.AMI_ID }}" \
          -var="key_name=${{ secrets.EC2_KEY_NAME }}" \
          -var="s3_bucket_name=${{ secrets.S3_BUCKET_NAME }}" \
          -var="instance_count=${{ secrets.INSTANCE_COUNT }}"

